version: '3.4'

services:
  product-service:
    image: 129851735808.dkr.ecr.us-east-1.amazonaws.com/product-service:latest
    platform: "linux/amd64"
    restart: on-failure
    ports:
      - "8081:8081"
  
  user-service:
    image: 129851735808.dkr.ecr.us-east-1.amazonaws.com/user-service:latest
    platform: "linux/amd64"
    restart: on-failure
    ports:
      - "8080:8080"
      
  delivery-service:
    image: 129851735808.dkr.ecr.us-east-1.amazonaws.com/delivery-service:latest
    platform: "linux/amd64"
    restart: on-failure
    ports:
      - "8082:8082"

  frontend:
    image: 129851735808.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
    ports:
      - "80:3000"
    depends_on:
      - product-service
      - user-service
      - delivery-service