name: Team Group-P8-07 CI tasks
on:
  push:
    branches:
      - main
      - develop  # Add the 'develop' branch
      - user-service
      - product-service
      - delivery-service

jobs:
  build-backend-delivery-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission to mvnw
        working-directory: Backend/DeliveryService
        run: chmod +x mvnw
      - name: Build with Maven
        working-directory: Backend/DeliveryService
        run: ./mvnw --batch-mode --update-snapshots package

  build-backend-product-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission to mvnw
        working-directory: Backend/ProductService
        run: chmod +x mvnw
      - name: Build with Maven
        working-directory: Backend/ProductService
        run: ./mvnw --batch-mode --update-snapshots package

  build-backend-user-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission to mvnw
        working-directory: Backend/user-service
        run: chmod +x mvnw
      - name: Build with Maven
        working-directory: Backend/user-service
        run: ./mvnw --batch-mode --update-snapshots package

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Tests 
        working-directory: frontend 
        run: npm ci
      - run: npm test
        working-directory: frontend
