name: Team Group-P8-07 CI tasks
on:
  push:
    branches:
      - main
      - develop  # Add the 'develop' branch

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Tests 
        working-directory: frontend 
        run: npm ci
      - run: npm test
        working-directory: frontend
